### ISSUE TITLE
Adventure mode Rebalance enemy drops

### ISSUE THREAD

**Issue by austeregrim** [Card-Forge/forge#1115]
**Is your feature request related to a problem? Please describe.**

- I'm always frustrated when enemies only drop the good stuff.

**Describe the solution you'd like**

- Enemies shouldn't **always** be dropping valuable items. 
- Lands, gold, and a lot of common cards should be dropped far more often than a full stack of cards with uncommons and rares.
- On rare occasions a drop of an unopened booster pack, or a rare card.
- In the same vein lootable spots like hidden treasures (not guarded by enemies.) or searchable pots and places in town might hide items, in lieu of enemies always dropping rare cards.

**Describe alternatives you've considered**

- Asking neighbors for a cup of sugar... but all I ended up with was a bunch of cups of sugar.

- What am I going to do with all this sugar?!

**Additional context**

**Comment by austeregrim** [comment]
As some people have mentioned in the discord, there needs to be a good balance between 'grind' and 'progress'. 
I'm still in the opinion of lands and gold should always be a drop but not count towards any other awards. All other cards should be able to drop, with a heavy lean towards what the enemy had in his deck, with a random chance of any card in the legal editions of the plane.

I'm also heavy on utilizing non-match mechanics to gain additional cards, especially rare or valuable cards. (Hidden items, random finds, checking the village well for a card.) And even locations that aren't a village or a dungeon... maybe someones house, cabin, a beach, a roadside, mountain climb... there's a lot of good assets that are in use that could be modified slightly to make them unique locations to "dungeon crawl", even if they aren't a dungeon or full of enemies.

**Comment by rikimbo** [comment]
This is somewhat impacted by the bug fixed in [!1417](https://github.com/Card-Forge/forge/pull/1417), which meant enemies were giving more deck rewards than intended.

That said, when I was playing, I also found the rewards too generous, especially:
1. Defeating opponents that had the shock lands in their deck meant it was easy to fill out my mana base.
2. I defeated enough snakes that I got 3-4 copies of [Hexdrinker](https://scryfall.com/card/mh1/168/hexdrinker) very quickly, and that drastically changed the power level of my deck. 

Playing around with the ratios is somewhat doable in enemy [reward configs](https://github.com/Card-Forge/forge/wiki/Create-Rewards). I'm playing around with something like this, which makes uncommons and rares from decks drop less frequently, especially rare lands:
``` json
        "rewards": [
                {
                        "type": "deckCard",
                        "probability": 1,
                        "count": 2,
                        "addMaxCount": 4,
                        "rarity": ["common","basicland"]
                },
                {
                        "type": "deckCard",
                        "probability": 0.5,
                        "count": 1,
                        "addMaxCount": 2,
                        "rarity": ["uncommon"]
                        "cardTypes": ["Creature", "Artifact", "Enchantment", "Instant", "Sorcery"]
                },
                {
                        "type": "deckCard",
                        "probability": 0.25,
                        "count": 1,
                        "addMaxCount": 1,
                        "rarity": ["rare"]
                        "cardTypes": ["Creature", "Artifact", "Enchantment", "Instant", "Sorcery"]
                },
                {
                        "type": "deckCard",
                        "probability": 0.1,
                        "count": 1,
                        "addMaxCount": 0,
                        "rarity": ["rare"]
                        "cardTypes": ["Land"]
                },
                {
                        "type": "gold",
                        "probability": 0.3,
                        "count": 10,
                        "addMaxCount": 90
                }
        ],
```
The caveat is that the Fortune Coin item affects this disproportionately, since it increases the amount of deck cards you get and it applies to each individual reward defined in the config. I'm not sure if it's a bad thing, but it's counter-intuitive.

**Comment by TheSAguy** [comment]
I'm in total agreement on this one. I'm playing SNAPSHOT build 912 and have several times gotten 2 or 3 rares per enemy drop.
It does not look like the code can split drops per difficulty level, that might be nice to implement.

Land can easily be bought and I'm actually not a fan of the big land drops. As mentioned above, it's a fine line between grinding and progress, but with all the shops and not losing any cards due to Ante, I would definitely like to see less rare drops please.
