### ISSUE TITLE
Temple of the Dragon Queen ETBs tapped even if a Dragon is on the battlefield

### ISSUE THREAD

**Issue by Agetian** [Card-Forge/forge#1396]
**Describe the bug**
When you play Temple of the Dragon Queen with at least one Dragon already present on the battlefield and with no Dragons in your hand, Temple of the Dragon Queen will always ETB tapped.

**To Reproduce**
1. Give yourself Temple of the Dragon Queen and put at least one Dragon on your battlefield via dev mode tools.
2. Play Temple of the Dragon Queen, choose the replacement ability which allows you to play it untapped if a Dragon is controlled.
3. Temple of the Dragon Queen will enter the battlefield tapped.

**Expected behavior**
Temple of the Dragon Queen should enter the battlefield untapped.

**Additional context**
Debugging shows that the problem is apparently circa lines https://github.com/Card-Forge/forge/blob/bafa5d2b1604dbf94ba319da41482f39ebdc3e31/forge-game/src/main/java/forge/game/ability/AbilityUtils.java#L2738-L2746 
The game tries to utilize the getLastStateBattlefield method of the spell ability object (sa), but that returns null, which makes the game believe that no cards are present on the battlefield. I'm not sure why the latter happens - either the last state isn't yet set for the spell ability at that point, or it may have been reset by some preliminary call, not sure how to debug that part properly.

**Comment by Hanmac** [comment]
@Agetian @Northmoc my gut is telling me that the problem lies within where SA is pointing to:

https://github.com/Card-Forge/forge/blob/bafa5d2b1604dbf94ba319da41482f39ebdc3e31/forge-gui/res/cardsfolder/t/temple_of_the_dragon_queen.txt#L5-L6

The Check for LastState there is on the Ability of Line6, but LastStateBattlefield for the ReplacementEffect is, as far as i know, only set for the Root one.

so for fixing the problem, the piece in AbilityUtils should probably call getRootAbility to get the one where LastState is set?

**Comment by Agetian** [comment]
Changing 2740 and 2743 in AbilityUtils to use sa.getRootAbility() instead of just sa (in the replacement effect branch) seems to solve the issue. Should we go down this route?

**Comment by Hanmac** [comment]
@Agetian yeah that should be enough
