### ISSUE TITLE
Adventure Mode: Spawning / Disappearing Dungeons

### ISSUE THREAD

**Issue by TheSAguy** [Card-Forge/forge#1512]
**Is your feature request related to a problem? Please describe.**

If I'm not mistaken, dungeons are pre-spawned at the start of the game and don't disappear. 
Currently all you need to do is find a dungeon near a city, and keep doing it until you clear it out, just duck into the town and heal if you lost a battle. There is no incentive to fighting another battle after losing a fight. Just heal and repeat. 

**Describe the solution you'd like**

I'd like to have Dungeons randomly spawn as you travel the world, but also disappear when you leave them.
This way life loss is meaningful between fights. Now you need to clear our a few enemies before leaving.
Removing dungeons once visited will also keep the map cleaner.

**Describe alternatives you've considered**

Change the dungeon icon if you've already entered it. 

**Additional context**

**Comment by TrueFuFLeaderG** [comment]
Would be an interesting idea but,
dungeons are/should not be designed to only allow one try, if a door is closed are a requirement is not met.
Right now dungeons are a bit of a mess but i hope to improve that in the future.

I get that the running back to the town is kind of annoying but is there to not try it until you have a good hand.

The alternative is do able, but you probably have to mark it  you self on the map because it is hard to tell if a player is done with the dungeon
