### ISSUE TITLE
702.103g If a bestowed Aura phases in unattached

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#1976]
> 702.103g If a bestowed Aura phases in unattached, it ceases to be bestowed. See rule 702.26, “Phasing.”

> The Question was at what point the Bestow stops being a creature, while still phased out or not? i mean it shouldn't probably matter but i think the unbestow does happen while still phased out

You're right, it seems currently there will be a short window where it still exists as Aura :/
I think I'll look into that in another PR after

_Originally posted by @tool4ever in https://github.com/Card-Forge/forge/issues/1973#issuecomment-1328342983_

**Comment by tool4ever** [comment]
Test case looks like this:

![image](https://user-images.githubusercontent.com/8506892/204160480-e4fa7cb9-83e7-4f9f-8198-906688a0fc05.png)

Currently on the next upkeep the Crocodile will trigger, but it probably shouldn't?

**Comment by Hanmac** [comment]
@tool4ever i mean this difference:

* The Bestow does phase out
* You remove the enchanted creature
* CURRENTLY the Bestow does stops being an Aura and becomes a creature, this is incorrect
* Then the Bestow does phase in as a creature.

like i said it shouldn't make a difference because it always should phase in as a creature

The thing with the Crocodile, yeah it probably shouldn't trigger

**Comment by tool4ever** [comment]
nono, it's still an aura while phased out:

![image](https://user-images.githubusercontent.com/8506892/204208614-49b0fe1d-c490-4a27-8d4f-38e1a70b7345.png)
