### ISSUE TITLE
NSC: Lagrella, the Magpie

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#204]
> When Lagrella, the Magpie enters the battlefield, exile any number of other target creatures controlled by different players until Lagrella leaves the battlefield. **When an exiled card enters the battlefield under your control this way, put two +1/+1 counters on it.**

>  "This way" refers to cards entering the battlefield as a result of Lagrella leaving the battlefield.
>  The last part of Lagrella's ability is a delayed triggered ability that is set up as its enters-the-battlefield ability resolves. It will trigger when Lagrella leaves the battlefield even if it's somehow lost its abilities or become a copy of something else.

* I Don't know if that counts as ETB trigger for cards that shutdown ETB Triggers like Hushbringer.
* Even if they are ETB Trigger, they shouldn't be affected by Panharmonicon effects, because these shouldn't apply to DelayedTrigger
* Either way it should probably be done in untilHostLeavesPlayCommand, But can't use cause there.

**Comment by tehdiplomat** [comment]
My instinct is that: 
Yes its an ETB trigger. 
I think it should also be affected by Panharmonicon, since the Delayed Trigger would LKI to see what created it and its a permanent you control?

This is just a new oblivion ring effect that can target one other creature per opponent, and when it leaves all creatures that come back under you control gain extra counters? That doesn't sound that awful?

**Comment by Hanmac** [comment]
> 603.2e Some effects refer to a triggered ability of an object. Such effects refer only to triggered abilities the object has, not any delayed triggered abilities (see rule 603.7) that may be created by abilities the object has.

while it is an ETB trigger, delayed trigger shouldn't apply for Panharmonicion
