### ISSUE TITLE
Compleated PW can't gain their full strength from counter doublers

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#2481]
https://www.reddit.com/r/askajudge/comments/tg0k5i/tamiyo_compleated_sage_and_doubling_season/

Apparently doubling them can be done before compleated.

@Hanmac 
seems like a very ugly thing for us
Compleated might have to be changed from Moved to AddCounter?

**Comment by Hanmac** [comment]
the Reddit is wrong:
> “If this permanent would enter the battlefield with one or more loyalty counters on it and the player who cast it chose to pay life for any part of its cost represented by Phyrexian mana symbols, it instead enters the battlefield with that many loyalty counters minus two for each of those mana symbols.”

its an ETB Replacement effect, not an replacement effect for AddCounter

**Comment by tool4ever** [comment]
Yea it feels wrong but another Judge also agrees :/

https://www.youtube.com/watch?v=oKmgVWH_2o8

I wish Rules Manager would give more anwers again

**Comment by Hanmac** [comment]
i can't watch the video yet but i already disagree

**Comment by Hanmac** [comment]
This Judge also says that it works:
https://magicjudge.tumblr.com/post/708883006201446400/hello-if-i-have-doubling-season-and-elesh-norn
https://magicjudge.tumblr.com/post/708892827330985984/hello-if-i-have-doubling-season-and-elesh-norn

but i still don't think that would work, because Doubling Season DOESN'T change how the card enters the battlefield

**Comment by Hanmac** [comment]
it can't work that way they suggest because otherwise multiple "additional counters" effects would interact with doubling season, and they don't

**Comment by Hanmac** [comment]
I already have some plans for this to make ReplaceAddCounter Effects work when entering the Battlefield while doing ETB replacement on the same event

but that's probably not something that can be done fast

**Comment by tool4ever** [comment]
Personally I think we have more important bugs in this area anyway, just wanted to document it 🤔

**Comment by Hanmac** [comment]
My Bigger Plan for this:
* make etb counter table be part of the replacement parameters
* then have "additional counters" fill that table instead
* then have getReplacementList return ReplaceAddCounter ones on the counter table (or a sub map of it)
* I need to check how CantPutCounter should be handled there, if it should stay a static (with lki?) or if it should be an replacement effect with CantHappen (but when we need to be careful not messing with the original entering-the-battlefield event)

then the table is already filled with the counters (multiplied by effect) then add them to the card, skipping replacement effects, and just run the triggers

**Comment by Hanmac** [comment]
the problem i now see is this one:

if multiple cards (creatures) entering the battlefield at the same time, and they all get affected by "additional counters", how do the replacement effect for the counter doubler react to this?
is the One Card entering the Event that gets replaced or more? And how are the Replacement Effects Ordered?
If it can be Ordered differently 

Because if the Replacement Effect should replace multiple creatures entering, then we need to make a BIG Change on the moveTo Effects

Semesters End for example would put multiple creatures into play with additional counters.

===
Also for CantPutCounter, how does Melira, Sylvok Outcast interact with cards that enter with additional -1/-1 counters when entering at the same time?

**Comment by tool4ever** [comment]
I'd say that since the Rules have no special case for this it falls under the part to treat "Can't" _like_ RE...

A) that means it should only work with _Melira's Keepers_ because this one can only replace herself

B) but not with _Melira, Sylvok Outcast_

➡️  I tested both cases with _Pyrrhic Revival_ , no counters

➡️  if this holds true it might be best to rework it with `ReplacementLayer.CantHappen` because you already added support for that case with `Mowu` in `ReplaceAddCounter`

**Comment by Hanmac** [comment]
> I'd say that since the Rules have no special case for this it falls under the part to treat "Can't" _like_ RE...
> 
> A) that means it should only work with _Melira's Keepers_ because this one can only replace herself
> 
> B) but not with _Melira, Sylvok Outcast_
> 
> ➡️ I tested both cases with _Pyrrhic Revival_ , no counters
> 
> ➡️ if this holds true it might be best to rework it with `ReplacementLayer.CantHappen` because you already added support for that case with _Mowu_ in `ReplaceAddCounter`

For Pyrrhic Revival have you tested it in which order they enter the battlefield? (for this you need to stack your graveyard?)
Melira trying to enter the battlefield before cards like Hatchling that enters with -1/-1 counters?
or Melira entering after the Hatchling?

* For Mowu, the ReplaceAddCounter has some logic for ValidCard$ Card.Self, might be done similar for CantPutCounter
* for  `ReplacementLayer.CantHappen` , the problem is that like i said we need to be careful that we didn't mess with the outer ETB replacement

**Comment by tool4ever** [comment]
Because as static it should affect both with _Noxious Hatchling_ unfortunately depending on the order (by the engine even if it should be simultaneous) it will either ETB with or without counters

**Comment by Hanmac** [comment]
One Creature Entering will be One Event
Putting Counters on it will be the same Event (maybe?)
ETB Counters of one creature will be one ALL Counters trigger
CantPutCounter probably can't be an Replacement Effect on the same level because then it only could apply once, (while you might stack etb counter replacements differently)
So the Static probably need to learn how to use either Look back at what it was, or look forward at the time of ETB Counter effect

So i might not need to use GameEntityCountersTable, but can use the ETBCounter Table on the Card (i wanted to separate it)


Bioessence Hydra on the field, two Planeswalker enter at the same time causes TWO all counters trigger
Because they are two events

**Comment by Hanmac** [comment]
for ETBCounter on Card (Currently a `Table<Player, CounterType, Integer>`) i probably still use GameEntityCounterTable (`Table<Player, Entity, Map<CounterType, Integer>>`) so i can continue to use the other Functions inside ReplaceCounter that where looking for `Map<Player, Map<CounterType, Integer>>`

just need to see where i can put the `canReceiveCounters` to look backwards or forwards

**Comment by Hanmac** [comment]
@tool4ever 

With the new `Innkeeper's Talent` + `Vraska, Betrayal's Sting` combo, we might look into this again.

For this to work, ETBCounter on Card might need to be passed as an extra parameter?

Then ReplaceAddCounter somehow needs to interact with ReplaceMoved?

Maybe if we move the modeCheck?
https://github.com/Card-Forge/forge/blob/8bc31ee56759d08245e4d4f8f2c0296d15bafaa0/forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java#L139

**Comment by tool4ever** [comment]
What happens when it turns negative might depend? 🤔
- if you still have enough _Oath of Gideon_ RE to apply after it can turn positive again
- if you only have RE like _Doubling Season_  with "would put one or more counters" left they could no longer apply
