### ISSUE TITLE
Game crashed mid-duel due to Vizier of Deferment played in precombat main phase

### ISSUE THREAD

**Issue by LtLukoziuzU** [Card-Forge/forge#2565]
Happened roughly 30 minutes from posting this, game did offer me a chance to save it and report it, but I'm not sure if either button did anything - files that I think were supposed to hold the report are completely blank:

![image](https://user-images.githubusercontent.com/55747413/221370795-5208a29e-68c0-40a7-b643-ea3d581e6be9.png)

So I'm making this to make sure it doesn't get missed - if report button actually did something, would be nice to know so. To describe what happened: Was playing against AI in Adventure mode, and the duel was way underway, both of us having massive boards at a stalemate (two white token decks). However, once AI successfully casted Vizier of Deferment:

![image](https://user-images.githubusercontent.com/55747413/221370930-2561acf9-55a4-482e-8f35-94a311f677ea.png)

It crashed while trying to make the EtB happen, it having no valid target as it was AI's precombat main phase (not sure if targetting specifically was the issue - just know that priority passed for it to be cast and placed on battlefield, and then crash happened). 

Win 10, 1.6.56-SNAPSHOT-02.23, Insane Difficulty Adventure Mode

**Comment by tool4ever** [comment]
If you're playing with internet reporting may give us some debugging details.
But it's still good to open an issue so we can ask more questions if needed.

That said I could not reproduce this in a simple scenario, so the steps that can lead to this would probably be needed if you're able to find them.

Otherwise it might have also been caused by another card but I'll leave this open for a while...

Also note that the current phase has nothing to do with target legality.
