### ISSUE TITLE
Assist

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#3121]
> 702.132. Assist
> 702.132a Assist is a static ability that modifies the rules of paying for the spell with assist (see rules 601.2g-h). If the total cost to cast a spell with assist includes a generic mana component, before you activate mana abilities while casting it, you may choose another player. That player has a chance to activate mana abilities. Once that player chooses not to activate any more mana abilities, you have a chance to activate mana abilities. Before you begin to pay the total cost of the spell, the player you chose may pay for any amount of the generic mana in the spell’s total cost.

Some notes to think about it:

- It shouldn't reduce the amount of mana spent to cast this spell. Or otherwise, the the mana reduced for you need to be added later
- We probably need to refactor "mana is spent" cards like Pyromancer's Goggles with: `When that mana is spent to cast a red instant or sorcery spell, copy that spell and you may choose new targets for the copy.` like you are not spending it, but you still should get the trigger? Also it still should respect the Mana Restrictions
- AI should consider Assist and possible team members when choosing a value for X

**Comment by tehdiplomat** [comment]
One thing I've noticed from my experiments is because the AI is constantly just processing its costs, it requests the Human to pay for an Assist spell it may not even be capable of paying for itself. (e.g. If I get 3 more mana, I can affford this thing), but instead the AI will be tapped out and be like "Hey help me pay for this thing". 

I think for the initial iteration, the AI should:
- Never request Asistance 
- Offer to pay some of an allies spell. Probably worth comparing what is being played with any fast effcts/abilities. Mana efficiency is probably key here. 
- Never pay for opponents assistance requests

AI Iteration
- Some of the non-permanents consider giving Assistance to opponents if its valuable for the AI for the effect to occur. [Generally not true for Creatures](https://scryfall.com/search?q=o%3Aassist+-t%3Acreature&unique=cards&as=grid&order=name)

1. Bring Down - Attempting to destroy an opponents creature (especially if its a problematic one)
2. Game Plan - Probably only timetwister if you are dying soon and need to find an answer
3. Gang up - Targeting an opponents creature
4. Huddle up - AI gets to draw a card
5. Out of Bounds - Countering an opponents spell
6. Play of the Game - AI board state is poor
7. The Crowd Goes Wild - Some of the AIs creatures are targeted?

- Don't request Assistance in a 1v1 duel
- Primarily request Assistance to Allies with open mana
- Once Assistance has been denied, don't ask again for that turn
- In a multiplayer game with no allies, ask the player with the "worst board state" who has open mana for Assistance. Maybe some type of weighting based on people who will untap sooner?

For Humans:
- Force Human players to request a specific number when casting an Assist spell (almost like Announce)
- Allow Human players to spend any amount 0-N where N is the amount of generic mana spendable on the spell, but tell them how much has been requested. 

Overall
- Make sure mana payments are getting linked to the spell itself for triggering things.

**Comment by Hanmac** [comment]
Yeah, especially parts of the AI is used to predict if Human can play the card.

or for `The Crowd Goes Wild` you should be able to choose X greater than your available Mana ?
