### ISSUE TITLE
Plane card doesn't leave game when owner does

### ISSUE THREAD

**Issue by Klisz** [Card-Forge/forge#3318]
**Describe the bug**
In a Planechase game, when a player who isn't the planar controller but does own a face-up plane card leaves the game, that plane continues to exist. This causes additional issues; once a player planeswalks from such a plane, they'll planeswalk to a new plane, but the previous one will remain face-up in the command zone as well. Furthermore, the player who planeswalked will remain the planar controller of the old plane even after they pass turn, but the new plane will change planar controllers as normal.

**To Reproduce**
Begin a Planechase game with at least three players. Pass the turn such that the planar controller and the owner of the current plane are different players. Have the owner of the current plane leave the game.

**Expected behavior**
As per rule 901.10, the current plane should be removed from the game and the planar controller should turn the top card of their planar deck face up. (This already seems to behave correctly if the player who leaves the game is the planar controller as well as the owner.)

**Desktop (please complete the following information):**
OS: Windows. Tested on build 1.6.5.7-SNAPSHOT-06.18 in both forge and forge-adventure.

**Comment by Agetian** [comment]
The culprit here appears to be the implementation at line 804 of Game.java:

```
            if (c.getController().equals(p) && (c.isPlane() || c.isPhenomenon())) {
                planarControllerLost = true;
            }

```

The issue here is that during each player's turn, the controller of the plane card is set to the current player (not sure if this is actually correct behavior), while the owner of the plane card is correctly set to the "plane controller". For example, if I change "c.getController().equals(p)" in the code above to "c.getOwner().equals(p)", the fact of the planar controller losing the game appears to be correctly registered in the case described in the original post. However, as I'm not the best person to deal with in-depth game mechanics, I'm not sure if this is actually the desired solution or this needs a bigger rewrite when it comes to determining/setting the controller of the current plane card.

**Comment by tool4ever** [comment]
There are two cases we need to handle:
- if the planar controller lost it must be updated with a new one
- if the plane was owned by the loser walk to a new one

**Comment by Agetian** [comment]
Those two aspects seem to be handled below, with the following code block:
```
        if (planarControllerLost) {
            getNextPlayerAfter(p).initPlane();
        }
```

**Comment by tool4ever** [comment]
Hehe, it's actually your code ;)
If only the first case happened you shouldn't get a new plane (and then perhaps it should still be done with `Player.planeswalk()` for triggers...?)

**Comment by Agetian** [comment]
Hehe, I already forgot XD  Yeah, most likely, and I agree about Player.planeswalk.

**Comment by Agetian** [comment]
Checking out the code for Player.planeswalk, it expects a SpellAbility which can't be null since it's used in the code (for the last state), I'm not sure if it would be OK to simply pass a null last state to Player.java:2701-2702 :/
