### ISSUE TITLE
AI hates hamsters

### ISSUE THREAD

**Issue by Ampersandnz** [Card-Forge/forge#3353]
I've been playtesting a deck with https://scryfall.com/card/clb/285/minsc-&-boo-timeless-heroes as the commander

When the AI plays this card, it almost always chooses to sac Boo for 1 damage to an opponent + draw a card, even if that leaves the planeswalker completely unprotected and dead to a return attack.

The only times I've ever seen it use the +1 buff ability is when that enables a lethal attack on an opponent, but in the vast majority of situations it would be stronger than using the -2 to only get a single card

**Comment by Hanmac** [comment]
@Agetian a general Sacrifice logic so it doesn't sacrifice if the power is too low?
(or does it need extra logic if it can use the sacrifice for leathal?)

or does it need more AI logic to not have it unprotected?

Also it should play this card in Main1 ?

**Comment by Ampersandnz** [comment]
I'm not sure what the answer is but it seems to be valuing the 1 card draw way too high vs the option of having a large creature

**Comment by Agetian** [comment]
Hmm yeah, I think I can add a logic there that will make it sac for lethal damage (to creatures or opponents). I'll also throw in the PlayMain1 hint. An interesting observation: the Sacrifice ability on that card doesn't have Defined$ You (though it seems to be implied in how the text is phrased (When you do, if......). This actually makes the thing skip most of the AI logic checks. Is that intentional (I mean the missing Defined$ You)?

**Comment by tool4ever** [comment]
Imo the logic there needs to be updated:
```
        final String defined = sa.getParamOrDefault("Defined", "You");
        final String valid = sa.getParamOrDefault("SacValid", "Self");
        if (valid.equals("Self")) {
```

**Comment by Agetian** [comment]
Ah, yeah, sounds like a plan :)

**Comment by Hanmac** [comment]
@Agetian can this issue closed for now? or should this kept open to be extended more?

**Comment by Agetian** [comment]
I think safe to close for now.
