### ISSUE TITLE
Consecrate // Consume probably missing A.I. logic

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3370]
**Describe the bug**
Opponent cast Consume targeting me. I have zero creatures on the field, whereas each of the other opponents have at least one. The card will do literally nothing here.

**Expected behavior**
To at least cast the spell targeting a player with a creature to sacrifice.

![Screenshot_20230630_012256](https://github.com/Card-Forge/forge/assets/92389638/ef197173-feb0-4ca9-ac9f-dc6c83fd82f4)

**Comment by tool4ever** [comment]
@Agetian 
imo you could try to rewrite the script without Pump + ChooseCard
that might already help

**Comment by Agetian** [comment]
Hmm, I'm not quite sure how, I'm afraid... ChooseCard is used there because of greatestPowerControlledByRemembered, which is the only way seemingly implemented at the moment for that kind of a thing (haven't found any script that would use a different approach). Avoiding Pump+ChooseCard+Sacrifice will probably involve something like greatestPowerControlledByTargeted then?

**Comment by tool4ever** [comment]
yea that should already work
