### ISSUE TITLE
AI vs Defense of the Heart

### ISSUE THREAD

**Issue by schnautzr** [Card-Forge/forge#3441]
Defense of the Heart is 4-drop endgame card. If the opponent has 3 or more creatures in play as you start your turn, you sac DotH and drop two massive endgame creatures on the board.

The AI doesn't account for the threat of what might be in its owner's library. It should assume the worst, and avoid making this ability trigger if possible.

**Comment by Agetian** [comment]
This one is slightly tricky to get right, to be honest. I mean, it's definitely possible to make the AI stay on 2 creatures or less in the presence of this card, but in that case it'll most likely fall to the opponent going wide rather than beefy. Depending on the AI deck, it may or may not be able to deal with the two creatures that are coming from the trigger (using direct removal, bounce, or whatever else that may deal with them), but if the AI consciously holds back on casting creatures for the rest of the game, it'll most likely fall behind very quickly on other terms :/ Thoughs, opinions?

**Comment by schnautzr** [comment]
Definitely agree! So many ways it could go. But for the AI to see that and throw out a puny 1/1 goblin as its third creature without planning any defense for coming storm seems silly.
