### ISSUE TITLE
AI makes Mite token in response but they can't block

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#3790]
i noticed multiple times that AI was trying to create Mite token in response to an Attack

but totally didn't notice that these Token can't block

**Comment by Agetian** [comment]
I'm currently investigating the issue with the AI creating a Phyrexian Mite token in response to an attack. It looks like CombatUtil.cantBlock doesn't account for the possibility of a static ability implementation of this, and I don't see an easy way to check for its presence... What would be the preferred way to test for a CantBlockBy static? Should I iterate over all possible attackers and test whether the static applies? That might be a bit expensive performance-wise. Another issue is that this kind of check doesn't seem to work for hypothetical conditions (e.g. a card object that doesn't exist on the battlefield yet), which complicates matters further, since we want to test the token before it's spawned on the battlefield. Assistance is needed with this, as it prevents from using the CantBlockBy / CantBlock static more extensively without breaking the AI.

**Comment by Hanmac** [comment]
@Agetian possible easy fix:
add attacker and blocker to the cards checked by 
https://github.com/Card-Forge/forge/blob/7c303d2fb9ce7439a4f1600789a6d63f9b2835c0/forge-game/src/main/java/forge/game/staticability/StaticAbilityCantAttackBlock.java#L147

with that, it should be able for the AI to use LKI of the possible token to check against?

**Comment by Agetian** [comment]
Umm, how exactly? I tried looking at that spot before but haven't found a working way to integrate it there... :/

**Comment by Hanmac** [comment]
Like this

https://github.com/Card-Forge/forge/blob/7c303d2fb9ce7439a4f1600789a6d63f9b2835c0/forge-game/src/main/java/forge/game/staticability/StaticAbilityCantBeCast.java#L44-47

**Comment by Agetian** [comment]
Yes, pretty much, I did a similar thing there.

**Comment by Hanmac** [comment]
> This needs additional AI support, I believe. There are many instances in the code where the AI can determine that a card can't attack only by the presence of a hidden keyword, and processing a static is tricky/expensive. Related discussion about the similar "...can't block" keyword/static dilemma: #3790 Any ideas, @Hanmac @tool4ever ? I still have no idea how to hook this up properly, and most likely don't have enough time to figure it out due to work pressure :/ The "CARDNAME can't attack" hidden pseudo-keyword is hooked up to the creature evaluator and various AI routines in AttachAi, SpecialCardAi, and elsewhere, so this needs to be patched up to avoid making the AI stupider if we switch all the relevant cards to the static effect :)

i can fix the functions later, then the AI just need to call the checks in the Can't Attack logic
