### ISSUE TITLE
Can someone explain the reason behind the new installer?

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3859]
I noticed that the new snapshot (which is all I ever run) has been changed from tar.bz2 to a jar installer and I'm wondering what the reasoning behind this is... I'm on linux and I personally liked the delete old folder, extract new version. Never had an issue and it always felt clean and simple.

Is it going to create the same snapshot folder if I execute it, and if it is, then why even bother changing it?

**Comment by kevlahnota** [comment]
The install wizard is convenient tool for most users. The user can also select the installation folder. Is there an issue on your end running the installer?

**Comment by TheLastNarwhal** [comment]
> The install wizard is convenient tool for most users (targeted for beginners). The user can also select the installation folder. Is there an issue on your end running the installer?

There doesn't seem to be any issues running it, per se. It's just more clicking through menus and then making the .sh executable (though this might just be a one time issue.) 

I know that I have to get used to this, because it's not going to change, but it was easier when it was a single extract.

**Comment by kevlahnota** [comment]
The manual extraction is easier for advanced users but most users are not extracting to new folder hence bugs popups on sentry having old resources while using new engine, while the installer always generate the new folder based on snapshot release (unless the user change the install path and point it to an existing install even knowing this would cause an issue). Gonna close this since this is not an issue for the installer.
