### ISSUE TITLE
Order reversed with spells that put cards onto the library from the graveyard

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#3883]
Windows, snapshot 10.02

I've noticed that multiple cards that allow you to put any number of cards from your graveyard onto your library have this same mistake. The spell works normally through targeting, and then opens the dialogue box for ordering. For example, with Gravepurge:

![image](https://github.com/Card-Forge/forge/assets/29505281/fd2d6ae8-6996-4d0a-bd0b-39ac3b3e51d8)

The box order is labelled "closest to top". However, when the spell resolves I draw the last one, and the order is reversed:

![image](https://github.com/Card-Forge/forge/assets/29505281/a7d3615f-d729-47fc-acb7-2ef03fa49c0b)

Clearly the "closest to top" is actually using it as "put into library first", so the result is that the order is reversed from what was input. Either the dialogue box text should be updated for these effects, or the order should be changed to respect the text.

Currently all of the following cards are affected this way (from [this search](https://scryfall.com/search?as=grid&order=name&q=%28oracle%3A%22put+any+number+of%22+oracle%3A%22cards+from+your+graveyard+on+top+of+your+library%22%29+%28game%3Apaper%29)):
- Bone Harvest
- Footbottom Feast
- Forever Young
- Frantic Salvage
- Gravepurge

**Comment by jumpinjackie** [comment]
I think Lim-Dul's Vault has the same problem #3733

**Comment by Samthere** [comment]
Good call! I can't check right now but I seem to remember Sylvan Library may have done the same.

**Comment by TheLastNarwhal** [comment]
It's definitely not just cards that go on top of the library from the graveyard. I've noticed it do this with several cards that stack deck top and everytime I order the way I think it's asking me to (which is exactly what you said) it ends up being the exact opposite of what I wanted. Sometimes it kills that game and I have to quit, like if it was needed for a combo and now that combo has failed due to improper ordering of deck top.
