### ISSUE TITLE
Can we have a symbol or note on which creature attacks which player?

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4069]
See title...

which creature is attacking whom is the single most furstrating feature in Forge... I cannot count how often my creatures attacked the wrong player because the UI was not clear about it. Its just a mess, sorry!

**Comment by TheLastNarwhal** [comment]
It is very clear which player your creatures are attacking if you have set up the targeting arcs.


![Screenshot_20231101_093119](https://github.com/Card-Forge/forge/assets/92389638/87336a35-fa2b-4292-ad76-6dc04c9e57e8)

----------------------------

On desktop, and possibly mobile (though I don't play that, so who knows?), click the "dock" panel and then click the last button, cycling through until you have the targeting arc set up that you desire. 

Note: your buttons will not look the same as mine, as I am using a custom skin. Should be similar enough though.

![Screenshot_20231101_093243](https://github.com/Card-Forge/forge/assets/92389638/4e45eabb-6923-43a2-8901-2718b4c3529f)

**Comment by Nymra** [comment]
oooh, nice. thanks. will check that for the desktop version that I am using. 

but when I see the android I m a bit jealous for the looks :D

**Comment by TheLastNarwhal** [comment]
> oooh, nice. thanks. will check that for the desktop version that I am using.

Sure, happy to help.

> but when I see the android I m a bit jealous for the looks :D

Don't be. I was forced to use it (mobile version) for a short while, and from what I can tell it's all flash and no substance. The ability of the user to control the how the playing field is set up is vastly superior in the desktop version compared to the mobile version.

Also, even though I think it's inferior and don't think you should, you can use the mobile version on your computer, if you *really* want to. Just launch the **forge-gui-mobile** jar instead of the regular jar.
