### ISSUE TITLE
Craft mechanic

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#4098]
> Craft abilities are activated abilities with costs that have a mana component as well as an additional "materials" component.
Craft abilities are written "Craft with [materials] [mana]", which means "[Mana], Exile this permanent, Exile [materials] from among permanents you control and/or cards in your graveyard: Return this card to the battlefield transformed under its owner's control. Activate only as a sorcery."
The back faces of some cards with craft refer to cards "used to craft" it. This refers to the cards exiled as part of the cost of the craft ability of the front face. Those cards are considered to be "used to craft" that permanent as long as they remain exiled and the permanent remains on the battlefield, even if the permanent's controller changes or some of its characteristics change (because of a copy effect, for example.)

**Comment by Hanmac** [comment]
i updated the description

the tricky part might be the "used to craft" thing, because it is similar to ExiledWith, but i think we can't use ExiledWith there, because the host card changed Zones

@tehdiplomat also i think we might a new Cost for this?

for the Amount, we might try to add some logic with "X+4" for "four or more"

**Comment by Hanmac** [comment]
@Northmoc can you show the state of your work as Draft PR so we can comment on it?
