### ISSUE TITLE
Forge doesn't recognise cards that have the letters á, É, é, í, ó, ú, û in their names 

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4365]
**Describe the bug**
Forge doesn't recognise cards that have the letters á, É, é, í, ó, ú, û in their names. It writes warnings that these cards aren't supported.

**To Reproduce**
1. Choose "Constructed"
2. Choose "Net Archive Modern Decks"
3. Choose deck with Lórien Revealed
4. See warning

**Expected behavior**
Forge should recognise cards that have the letters á, É, é, í, ó, ú, û in their names

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.60-SNAPSHOT-12.11

**Screenshots**

![lorien](https://github.com/Card-Forge/forge/assets/115870280/c9451678-55a7-490c-99bf-3678a0a9d4e6)
![lorien2](https://github.com/Card-Forge/forge/assets/115870280/828b06ad-8718-4213-98f4-d290b8c6f6ce)

**Comment by Hanmac** [comment]
@tehdiplomat we should probably add better Fallback Names for this

Or try to fix the existing logic

**Comment by tehdiplomat** [comment]
Didn't WotC get rid of all of these names? Why are they back?

**Comment by Hanmac** [comment]
Don't know 

Especially the û one never really left

I once saw the line of code that might need to be added

**Comment by Hanmac** [comment]
My train of thought:

* have the Cards the Umlauts still in the Card Texts
* but when importing into the Card DB, also add the normalized names to (another) List
* when Decks are loaded, also check the other List when searching for Cards
* when choosing a Card Name, should it be only the OG name, or also the normalized Name?
* if the normalized Name should be able to be chosen, then we may need to refactor this with sharesName. (or have the chosen Name be converted back into OG Name first)

**Comment by Nemesis666first** [comment]
> Didn't WotC get rid of all of these names? Why are they back?

In the Lord of the Ring set, a lot of names have diacritics, it's useful in particular to say sounds which are not in english.
And, with more Universes Beyond set incoming, they are not going to get rid of it. First, because they cant, and sec, because there will be probably more to come. Let's be used to it.

**Comment by tehdiplomat** [comment]
> Let's be used to it.

I Don't really appreciate the patronizing tone here. Forge has been around a long time and these characters have caused problems on and off throughout its time. I think I'm allowed a little bit of frustration when they appear back up and cause problems again.

**Comment by Hanmac** [comment]
i will try next week if i can get it working with extra names in the CardDb

**Comment by Nemesis666first** [comment]
> > Let's be used to it.
> 
> I Don't really appreciate the patronizing tone here.

I was using "let's" as "in general", like in "everyone should learn to appreciate and understand the deep interest of it" (Because its a beautiful things that J. R. R. T. understood himself).
So, it was not meant to be "patronizing", but, but but but, this is an interesting knowledge you got on yourself. If you felt it, you put yourself in this position, trying to read an unexistant deep meaning behind the lines.
But, thats an opportunity to learn and grow up about this subject (Now, this sentence is patronizing 😂🤣, I agree).

(Its also important to separated this subject from Forge, which is only a software which rely on a other cultural product, you talked about the frustration you felt, but its not linked to WotC, since it, itself, relies on a otheeer cultural product)

Some years ago, I was interested about all these diactics in vietnamese language, this lead to me to start learning it a bit, because it was so amazing to discover that it was "tone" written on a character !
This is the kind of experience which makes grow up, making us realizing how our languages and/or writing systems can be really "poor", or "rich", depending of our native language.
Nowaday, I'm learning japanese, so, when I see someone complaining about some "classical" diacritics (From latin letters, in particular), I can restrain my fingers from typing 🤣🤣🤣😂😂.
I cant end more easily that telling "take it easy bro, let's be used to it" (In a non-patronizing way of speaking).

**Comment by MorihiroS** [comment]
@Nemesis666first, something tells me that this is not a self-disclosure club, an eloquence club, or a therapy group. It's too extensive, too inappropriate. I suggest you stop here, because no one here needs it.
