### ISSUE TITLE
REQUEST pop Up Window on Board Wipe / Card Type? 

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4543]
Yeah, Forge is less than easy to work with UI wise, so I would love to see a feature where I could have a Pop-Up like when Mana is left in the pool when I want to proceed.

Especially with counterspells and stuff like teferis protection it is annoying to play the game since it is hard to see all the cards the AI spams out sometimes. 

Would be cool if there would be an option like that.
Board wipes would be easy to identify I guess...

I know, you pro Players will now cry at me for proceeding too fast, but you know, I use Forge for Fun and for testing my decks. I dont want it to simulate a tournament, especially when I play vs. AI.

Thank you

**Comment by TheLastNarwhal** [comment]
All of this already exists...

> Yeah, Forge is less than easy to work with UI wise, so I would love to see a feature where I could have a Pop-Up like when Mana is left in the pool when I want to proceed.

Go to your preferences and then under "Gameplay" you will find an entry called "Prompt Mana Pool Emptying." Check it so that you will now get that prompt.
![Screenshot_20240117_115219](https://github.com/Card-Forge/forge/assets/92389638/520a1537-a3e6-4c73-8e11-fa5134279269)

> Especially with counterspells and stuff like teferis protection it is annoying to play the game since it is hard to see all the cards the AI spams out sometimes.

As for the A.I. playing too fast, well... that's partly true, but also completely your own fault if you can't follow the action. There's a reason you're allowed to set up your stops and you click "ok" to resolve effects. If your stops are set up like mine are, you will never have an issue not being able to follow the plays.

The darker gray are the phases to be skipped and the light gray are the phases where it asks to proceed.
![Screenshot_20240117_115524](https://github.com/Card-Forge/forge/assets/92389638/8babea1f-ebd5-4dc2-a457-8db1ed8c558d)

**Comment by Nymra** [comment]
well, you say I skip phases too fast.
I say you dont read my post or your reply would have been more elaborate.

I m not stupid, I already set up the phases, but that is NOT helping at all. 

There is simply no easy way to fast and reliably see which card is currently played.
No options to create popups at least when certain card types are cast (I mean I can understand a certain lazyness to implement a possibly complex feature like "pop up asking to proceed when board wipe is cast" while I think it would greatly improve the game.
Having a feature that is like "Pop Up asking to proceed if ANY card is cast that target or affects (destroy etc.) one of my permanents, I think that would be lots easier and also make the game like 200% better and more fun to play.

Sorry, but the combination of not beeing able to even go SIMPLE steps back (where nothing happened yet basically), a thing which can easily happen even when playing carefuly is just adding up frustration with forge, sadly.

I dont want to be overly critical, I just hate posts like yours who think they are entitled while not even reading or understanding the OP in any way.
