### ISSUE TITLE
AI - Cards with BeforeCombat trigger often should be played in Main1

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#47]
![image](https://user-images.githubusercontent.com/103371817/163602382-d215d973-acae-4d0e-b494-b98c5058d9ae.png)

100+ cards seem to have phase triggers for BeforeCombat
A quick peek through the ones starting with "A" shows probably less than half have the PlayMain1 tag including many that would almost certainly want it. On the other hand, certain cards like Battering Ram wouldn't benefit from that tag... unless something else gave it haste, which starts getting pretty fussy.

Might be an issue of just a good once over of all cards with that trigger, or it might be better to add more AI code?

@Agetian thought you might find this interesting

**Comment by Agetian** [comment]
Hmm yeah I think this can in theory (and in practice) be detected and fixed in the "PlayMain1" code for the AI, through trigger detection. However, it's a little bit more complicated than just having the trigger - it may need haste or it may need something to give it haste or it may have to have a trigger that would benefit other cards... It may end up being too complicated for an algorithm that basically runs at every SA playability check, it may slow things down... Looking through the cards with the trigger and setting up/removing PlayMain1 where due is a longer, but most likely "faster" option from the point of view of runtime.

**Comment by Northmoc** [comment]
If we do a good solid once over, future card scripters and ForgeScribe will do a better job adding that line too

The general practice is almost always start from a similar card.

**Comment by Agetian** [comment]
Yep, agreed! I actually did a similar thing a couple times for the AI playability flags (since the AI changes over time and certain previously unplayable cards may become playable but are still marked RemoveDeck:All)
