### ISSUE TITLE
AI doesn't cast Batwing Brume

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4784]
**Describe the bug**
AI doesn't cast Batwing Brume when an opponent's creatures are attacked

**To Reproduce**
1. AI has 2+ untapped lands
2. AI has Batwing Brume
3. Player attacks with 3+ creatures
4. AI doesn't cast Batwing Brume

**Expected behavior**
AI should cast Batwing Brume for white and black mana (as possible) when an opponent's 3+ creatures are attacked or if this damage will be lethal. There should be multiple payment options for AI: for BW, for 1W (without B), and for 1B (without W).

**Additional context**
I think all cards that have mana payment in the text have similar problems (https://scryfall.com/search?as=grid&order=name&q=%28oracle%3Awas+oracle%3Aspent+oracle%3Ato+oracle%3Acast+oracle%3Athis%29+%28game%3Apaper%29).

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.60-SNAPSHOT-02.29

**Screenshots**

![Brume1](https://github.com/Card-Forge/forge/assets/115870280/a5f29041-9c29-4406-aa35-3060180979f2)

**Comment by tool4ever** [comment]
I don't understand these reports.
This card (like many others) is clearly marked as `AI:RemoveDeck:All`
You should be warned when you force that on it in a deck

**Comment by MorihiroS** [comment]
@tool4ever, and I don't understand your outrage. 
Since the card is marked as AI:RemoveDeck:All, it can't be coded?
And what do you mean, "these"?

**Comment by tool4ever** [comment]
I'm not really outraged...
If you don't appreciate me telling you you're wasting your time since us developers (well really anybody) can easily search for the affected cards then that's fine by me. Continue doing this for your pet cards by all means 🤦‍♂️

**Comment by MorihiroS** [comment]
@tool4ever, I'm not marking cards that should in principle be difficult for AI (Prismatic Ending, Rakdos Charm, Shadow of Doubt, and so on). I'm marking the ones that intuitively should be understandable by AI, but somehow aren't. For example, AI makes great use of Springleaf Drum, but for some reason it only puts it on the battlefield with Urza's Saga. 

They are not my "pet cards".  These cards are just played in decks, and often AI plays these decks poorly because of weird moments like this, which I don't think are hard to fix.

And I try to do what I can for the project. Now, for example, AI can fully play Aether Vial and Karn, the Great Creator, although there were some basic flaws. Now AI plays great with human decks and merfolk decks.

>Continue doing this for your pet cards by all means
> 🤦‍♂️
Oh, that's so constructive and inviting to communicate (no).

But according to your reply, I'm really wasting my time here volunteering and making requests that even the description of the card at the stack stopped being corrected....

**Comment by tool4ever** [comment]
In theory everything can be coded but unique stuff might not be worth the effort (what is "easy" for the AI depends on a few factors).

But I don't think you're understanding my point:
![image](https://github.com/Card-Forge/forge/assets/8506892/5d534c19-dc76-4ecd-b898-fd26c4b365bb)
Why are you ignoring this warning?

![image](https://github.com/Card-Forge/forge/assets/8506892/7a5d4867-7b2a-4cda-bedd-bc00647ebd89)
I know you're trying to help out but we don't need your reports for 2500+ of these cards...

While it is possible that some tagged cards have become playable, that would require additional/different research.

**Comment by MorihiroS** [comment]
>  Why are you ignoring this warning?
I'm not ignoring the warning, I'm considering it. But I can see that AI easily using Springleaf Drum, and the whole problem is that it doesn't cast it from hand.

Batwing Brume doesn't feel like a broken card either. Can't it be possible to make the card have 3 payment modes, or at least one, so that the AI uses it like Fog?

> I know you're trying to help out but we don't need your reports for 2500+ of these cards...
 
@tool4ever, even if I close all ~13 cards mentioned in the warnings (which is no guarantee at all that they will be noticed later), there are a  ~73 requests left, ranging from the simplest #4372 to #4152 and #4266.

**Comment by tool4ever** [comment]
- For _Springleaf Drum_ it is very likely the AI will cheat with it in some scenarios since mana abilities with these additional tap costs can make it miscalculate
- _Batwing Brume_ is a good example of a card that might look simple, but is actually implemented by 3 separate effects in Forge (additional RepeatEach because of the tricky variable life loss). Those would all need to be synchronized to reach a valid play decision but to make it even more difficult you have shard conditions for each half - so even more logic is needed to make the AI "lookahead" based on what colors it has for paying. Considering there are plenty of alternative Fog-like cards to put in AI decks the decision to not spend extra time on this one feels like a no-brainer

**Comment by MorihiroS** [comment]
@tool4ever, thank you for the detailed explanation! But what should I do with these requests? Should I close them as unrealizable? And the other ones too (like #4391)?

And what should I do with those ~73 requests that are not included in the warnings?

**Comment by tool4ever** [comment]
- scripts the AI can't play should probably be tagged after checking they're just not missing AiLogic params. For the last recent sets that part of "QA" hasn't really been enforced too strictly because there's just no way for our current manpower to keep up with the amount of cards & gimmick mechanics Wizards keeps throwing around
- already tagged scripts should (e. g. we can't prevent human from _Donate_ a bad one) not cause bugs. Ideally a developer extending an effect would always address any relevant AI impact. But because of what I said above the occasional iteration over them could still be a justified activity (though without randomly picking you'd need some background knowledge to understand recent changes in API or script refactors)

**Comment by Hanmac** [comment]
imo they should all be fixed in the future

but they have lower priority

**Comment by MorihiroS** [comment]
Card is marked as AI:RemoveDeck:All
