### ISSUE TITLE
Stormtide Leviathan

### ISSUE THREAD

**Issue by Nogarde-Delrone** [Card-Forge/forge#5064]
**Describe the bug**
At present if you cast Stormtide Leviathan It does not see itself having Islandwalk OR is not letting creatures with Islandwalk attack we're not sure which but we've (my friendgroup and I) have tested it twice to confirm.
**To Reproduce**
In a multiplayer game cast and resolve Stormtide Leviathan and either give it haste or wait one round and then attempt to declare an attack with it and you will be unable to.

**Expected behavior**
Stormtide Leviathan should be able to recognize itself and/or other creatures as having Islandwalk and allowing them to attack.
**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 -  Launcher
1.6.62-SNAPSHOT
**Smartphone (please complete the following information):**

**Additional context**
We also confirmed that creatures with flying CAN attack with stormtide Leviathan on the field, it only seems to fail to recognize islandwalk

**Comment by Hanmac** [comment]
@tool4ever  ugh i was afraid there was one of them that causes such problems

* for `Stormtide Leviathan` we need to be careful because "withKeyword" uses "hasStartOfUnHiddenKeyword" and with "Landwalk:Island" it would find "Landwalk:Island.Snow:snow" for "Snow Islandwalk" too
* try "hasKeyword" which should check for the exact Landwalk ability
