### ISSUE TITLE
Possible bug with Heaven Sent

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5218]
**Describe the bug**
To me this seems like a bug, but I might be misunderstanding what the card is actually saying, so...

I have Heaven Sent on the third chapter, one opponent with 30 life and two other opponents with 0 and -2 life. I thought I was going to draw 7 cards, since two opponents meet the criteria for the trigger, but instead it just exiled itself.

I should note that both of those opponents were already at that life total before the third chapter triggered.

**Expected behavior**
To draw 7 cards when an opponent has 0 or less life.

**Screenshots**
![Screenshot_20240508_103838](https://github.com/Card-Forge/forge/assets/92389638/ab903710-afd5-45b3-a4b6-06955b571c83)

**Desktop (please complete the following information):**
 - Version: forge-gui-desktop-1.6.63-SNAPSHOT-05-03

**Comment by dracontes** [comment]
> I should note that both of those opponents were already at that life total before the third chapter triggered.

Yeah, that's the issue here. Players who lose the game leave it entirely (CR [104.5.](https://mtg.fandom.com/wiki/Ending_the_game#Rules) & [800.4.](https://mtg.fandom.com/wiki/Multiplayer#Rules) ) so Heaven Sent's third chapter triggered ability will only see Jonathan in the circumstances you describe.

**Comment by TheLastNarwhal** [comment]
Ah, I didn't know that the players couldn't even be referenced. Thank you.
