### ISSUE TITLE
Adventure Mode: Placeholder name left in quest "What's Yours Is Mine"

### ISSUE THREAD

**Issue by thranur** [Card-Forge/forge#5244]
**Describe the bug**
In Adventure Mode, quest What's Yours Is Mine, the second task says "Defeat the $(enemy_2)".

**To Reproduce**
1. Get the quest What's Yours Is Mine
2. Open the quest book, see its details, second task

**Screenshots**
![quest-name](https://github.com/Card-Forge/forge/assets/33481653/e8689e01-9004-4d20-b35f-09eaced0ee09)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - Browser Firefox
 - Version 125

I'm running Forge 1.6.63-SNAPSHOT-05-14.

**Comment by konijn** [comment]
Similarly, the description of Donovan's amulet seems to be cloned and not updated from the red teleportation charm.
Edit: using any necklace charm mentions the mountains..

**Comment by Vhati** [comment]
Over a month ago, I remember seeing a placeholder on the banner upon entry in "Cidryl Shard Mines". The banner disappeared quickly. My impression was of seeing "$(...)" and I gathered it meant their captain. So apparently the OP's sentence was repeated on the banner.

I don't know what's going on, but I can point to some files involved.

[quests.json](https://github.com/Card-Forge/forge/blob/164d1573e0ee7e9d2eecb5520746cab9a2d740f4/forge-gui/res/adventure/Shandalar/world/quests.json#L9609)

> "id": 2,
> "name": "Defeat the $(enemy_2)"
> "description": "Find and defeat the leader of the pirates in the $(poi_1).",
> …
> "mixedEnemies": true,
> "POITags": [
> &ensp;&ensp;"Quest_ShardMines"
> ],
> "objective": "Defeat",
> …
> "enemyTags": [
> &ensp;&ensp;"Captain"
> ],

"poi_\*" and "enemy_\*" are expected and replaced in [AdventureQuestData.java](https://github.com/Card-Forge/forge/blob/164d1573e0ee7e9d2eecb5520746cab9a2d740f4/forge-gui-mobile/src/forge/adventure/data/AdventureQuestData.java#L242), where "\*" refers to "stage.id". There are "replaceTokens()" functions that ostensibly apply to both the "name" and "description", yet "name" isn't getting replaced in this particular case. Stage 1 was traveling to the mine, so I expect poi_1 and poi_2 would both say the same thing. And enemy_2 would be the enemy characterized in stage 2 by tags.

I'm fuzzy on how exactly those variables get their values assigned.

In [shard_mines.tmx](https://github.com/Card-Forge/forge/blob/32d732bbb19f05f8b4a9bd5a43619ef7d356bd79/forge-gui/res/adventure/common/maps/map/main_story_explore/shard_mines.tmx#L1219), neither of those terms exist, and the leader object's "enemy" value is "Pirate Captain".

In [enemies.json](https://github.com/Card-Forge/forge/blob/32d732bbb19f05f8b4a9bd5a43619ef7d356bd79/forge-gui/res/adventure/common/world/enemies.json#L21864) the leader is named "Pirate Captain" and has "questTags":[…, "Captain", …]. So that fits with the quest's "enemyTags", which sets criteria for who needs defeating.

In [points_of_interest.json](https://github.com/Card-Forge/forge/blob/164d1573e0ee7e9d2eecb5520746cab9a2d740f4/forge-gui/res/adventure/common/world/points_of_interest.json#L3518), the location points to "shard_mines.tmx" and has "questTags":["Quest_ShardMines"]. Matching stage 1 and 2 "POITags".

I don't recall any other faulty banners.

/EDIT: Minor revision.

**Comment by Vhati** [comment]
@konijn: sounds like #9016.
