### ISSUE TITLE
Behavior on Evolve mechanic on Propagator Drone incomplete

### ISSUE THREAD

**Issue by Shonjuku** [Card-Forge/forge#5557]
**Describe the bug**
When Propagator Drone enters the battlefield with existing creature tokens in play, the tokens do not get +1/+1 counters from Evolve. Propagator Drone specifically mentions in it's reminder text that they should see this creature enter and would trigger. Later creature ETBs trigger Evolve correctly, just not the original for Drone itself entering.

**To Reproduce**
1. Build a board state with Eldrazi Spawn or Scion creature tokens in play
2. Cast Propagator Drone and have it successfully enter the battlefield
3. No counters will be added to Spawns or Scions in play
4. Reference reminder text on Propagator under its ability. Specifically, 'Creature tokens you control have evolve. (They have "Whenever a creature enters the battlefield under your control, if it has greater power or toughness than this token, put a +1/+1 counter on this token." **_They see this creature enter_**.)'

**Expected behavior**
Existing creature tokens you control with less than 2 power or toughness should receive a +1/+1 counter on them when Propagator Drone enters.

**Screenshots**
![Untitled](https://github.com/Card-Forge/forge/assets/175186241/afc5b3b8-b6d4-489b-beaf-6d5655940599)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Version: 1.6.63
In the screenshot I have attached, you can see several creature tokens that qualify for Evolve with Drone's entry but nothing happened.

**Comment by tool4ever** [comment]
@Hanmac
I'm not sure if something broke or we just never had this case before?

The problem is after statics from new card get applied we only reset the triggers for itself. All existing cards will go through a round of trigger collecting without first.

Adding something like this here does fix it:
https://github.com/Card-Forge/forge/blob/7e200eae8bec038c50a2f6aa26877b5c08c3ff40/forge-game/src/main/java/forge/game/GameAction.java#L617-L619
```
        for (Card inplay : game.getCardsIn(ZoneType.Battlefield)) {
            game.getTriggerHandler().registerActiveTrigger(inplay, false);
        }
```

But can we safely do that? 🤔
