### ISSUE TITLE
Selecting "Commander" causes program to crash

### ISSUE THREAD

**Issue by 32squids** [Card-Forge/forge#5733]
**Describe the bug**
After downloading today's snapshot (7-30-24), selecting "Commander" as a game type causes the game to crash. Other formats do not.

**To Reproduce**
1. Open Forge
2. Click on "Commander"

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chromse
 - Version: Daily snapshot 7-30-2024

**Comment by TheLastNarwhal** [comment]
@32squids

There might be something wrong with your version. Perhaps when you unzipped it an error occurred? I just downloaded **forge-gui-desktop-1.6.64-SNAPSHOT-07-30** and I don't crash when I click on the Commander tab in the deck editor or when I click on Commander when selecting a format in Constructed.

I'm using linux, so that might be why I'm not crashing. It's possible there's an issue with Forge and Windows for this snapshot. More likely that your particular download was corrupted somehow though.

**Comment by tehdiplomat** [comment]
Without a crash log we can't really tell you anything. I would recommend re-downloading and extracting to a fresh folder

**Comment by 32squids** [comment]
@tehdiplomat That unfortunately didn't work. I tried re-downloading with today's snapshot, too, and I run into the same error. This difference today is that clicking on "Commander" doesn't crash the whole system, requiring a restart to close out of Forge or do anything else.

**Comment by tehdiplomat** [comment]
You will need to provide a log file.
