### ISSUE TITLE
Go-Shintai and AI

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#578]
`Go-Shintai of Hidden Cruelty` AI paid the cost even if AI was the only player with destroyable creatures

The Part that makes AI pay this cost need more thinking.

**Comment by Agetian** [comment]
This is an interesting issue, I'd actually probably need some input on how to best approach fixing this.

The issue is basically that ImmediateTriggerAi calls DestroyAi#doTriggerAINoCost to test this for viability, and the latter doesn't bail despite the absence of preferred targets because it thinks the trigger is mandatory (mandatory is set to "true", so DestroyAi lines 358-359 are not tripped).

Is there any way to detect from inside that DestroyAi call that this is an ImmediateTrigger with a cost?
The "mandatory = true" parameter is passed from ImmediateTriggerAi#doTriggerAINoCost (at line 49). One of the ways to possibly approach this would be to pass "mandatory = false" if a cost is detected on that ImmediateTrigger (since I don't think any of the costs are forced to be paid). What do you think?

**Comment by Agetian** [comment]
Doing something like this in doTriggerAINoCost of ImmediateTriggerAi seems to do the job:
```
            if (!sa.getPayCosts().getCostParts().isEmpty()) {
                return aic.doTrigger(trigsa, false);
            }
```

Not sure what would be the best way to detect the presence of an (optional) cost.

**Comment by Hanmac** [comment]
for such trigger it is mostly "if you pay, when you do" stuff, so each cost needs to be paid for the trigger to happen

**Comment by Agetian** [comment]
That's true, but our problem is that the AI is overly eager to pay even if it doesn't have good targets :) The reason it happens is because it always considers these triggers mandatory, which screws up further logic checks since they ignore meaningful/reasonable limitations. Passing mandatory=false for the playability check seems to be a viable option in order to make the AI properly consider playability in a non-forced way (so that if it decides to pay, it'll do stuff).

**Comment by Hanmac** [comment]
yeah, mandatory=false should do the trick (for now)

**Comment by Agetian** [comment]
Cool, I'll submit that a bit later today then. What would be the best way to detect the presence of a cost? Is the check above fine in your opinion?

**Comment by tool4ever** [comment]
A few cards like _The Restoration of Eiganjo_ are also written with UnlessCost$, they probably need to be updated for that to work

**Comment by Agetian** [comment]
Btw, if the generic fix at the ImmediateTriggerAi entry point is suboptimal because it may break other cards/interactions when it comes to AI playability, maybe it may be worth marking specific cards with AI logic and then only treating them as non-mandatory at this point for the purpose of AI logic check if the logic is set? Not sure what would be more preferable (depends on how many cards are affected either way, I guess).

**Comment by Agetian** [comment]
Yeah, I think that for now, we can simply check if ImmediateTriggerAi is on a subability, and if it is, then pass "false" for mandatory for the purpose of AI logic checks. What do you think?

**Comment by tool4ever** [comment]
Hmn, do you mean the other way around? For the card of this issue, sa will still be AbilityApiBased

Seems a bit complicated tbh, it's also not 100% guaranteed that it is Optional in that case (maybe scripter just did AB$ without Cost$ or OptionalDecider$ anyway)

**Comment by Agetian** [comment]
Hmm, then I'm not sure how to do this correctly ^^;  Can you please help?

**Comment by Agetian** [comment]
Ok, thanks a lot! :+1:
