### ISSUE TITLE
Can not update resource file when language is set to Chinese

### ISSUE THREAD

**Issue by kdmcser** [Card-Forge/forge#6091]
**Describe the bug**
Android snapshot version need to update apk and resource file everyday. If language is setting to Chinese, after the resource file is downloaded, game hang for a while and crash.

**To Reproduce**
1. Setting language to zh_CN and CJK fonts to Chinese.
2. check update
3. update the lastest version and the resource file
4. game crashed.

**Expected behavior**
game not crash

**Smartphone (please complete the following information):**
 - OS: Android
 - Version snapshot 0906

**Comment by Hanmac** [comment]
@kdmcser can you attach the crash so we can see what is wrong?

**Comment by kdmcser** [comment]
I dont know how to get the crash log in Android

**Comment by Hanmac** [comment]
Look for a file manager for Android, like Total Commander, with that you should be able to access the hidden folder for where the Android data is

**Comment by Hanmac** [comment]
@CCTV-1 @junytang can you try to look into this?

@kdmcser does the problem still happen?

**Comment by CCTV-1** [comment]
i try clean install forge-android-snapshot-2024-11-17,then i can't reproduce the problem.
maybe because this bug requires skipp restart(set language and font need restart forge)?
or restart forge,but setup font + forge check and install update, use too more memory, because OOM crash(generate CJK font need very many memory)?
