### ISSUE TITLE
Option to select default format, variant and player count

### ISSUE THREAD

**Issue by keineahnungking** [Card-Forge/forge#627]
**Is your feature request related to a problem? Please describe.**
I only play Commander and I have to always select that format when I restart Forge. Especially when playing multiplayer it is very annoying to start a new game when the default is 2 player Constructed.
**Describe the solution you'd like**
Similar to the option that lets you choose to skip the selection of classic or adventure mode by setting a default I would like an option to set the default format tab that is selected when you click on "New Game" and setting a default variant for Constructed as well as a default player count. This would save a lot of time.
**Describe alternatives you've considered**
Alternatively the player count and variant could be saved like the last played deck is so it doesn't have to be reselected every time.

**Comment by kevlahnota** [comment]
I'll add an option to save the last selected variants, so if you only play commander, and exit. Forge next startup will select Commander variant (or last used variants). I don't know about changing the default player count since it will slow down the startup if the preselected lobby player has a lot of decks.
