### ISSUE TITLE
Volatile Stormdrake bug - opponent doesn't pay energy counters but doesn't sacrifice creature.

### ISSUE THREAD

**Issue by Alkaraba** [Card-Forge/forge#6421]
Volatile Stormdrake enters, targets 5 MV creature (Marneus Calgar), player gets 4 energy counters, player doesn't pay any, creature isn't sacrificed. No object on board visible that would prevent the sacrifice effect.

Log
![image](https://github.com/user-attachments/assets/c63e1783-a25f-4768-89f3-d6e3b3d8aeee)

Boardstate
![image](https://github.com/user-attachments/assets/050b2e74-d82a-4e34-a0da-04e065e3985f)

Forge updated latest version.

**Comment by Agetian** [comment]
Hmm, a pretty strange issue, I might need some help on this one... So far, I debugged it as far as SacrificeAllAi decision goes, that routes through the chkAIDrawback path and always returns "true", so the AI confirms the fact that it will agree to play that part. However, the SacrificeAllEffect#resolve method never fires for some reason... I'm not sure if it's the issue with the "unless cost" code path in the AI somewhere, or with something else, and sadly, can't quite figure out how to debug this properly :(

**Comment by Agetian** [comment]
Alright, so this might be a deeper issue in the code that parses Unless cost parts. This has to do with the fact that the Unless cost which is formatted as UnlessCost<N> or UnlessCost<X> or something else like that, where N and X usually resolve to Count$ChosenNumber, but sometimes to something else (e.g. Volatile Stormdrake uses TargetedManaCost), never get parsed by the AI to a specific value. I tried hooking up some basic code to do the parsing via AbilityUtils.calculate into AiCostDecision where it decides to pay Energy, but that doesn't seem to work, e.g. for Volatile Stormdrake it doesn't work because the ability doesn't have set targets while inside this method (not sure why, I tried looking for targets in the parent ability but there is none). The "cheating" part is actually due to the fact that the AI proceeds with "PayEnergy: 0" when it can't figure out how much it needs to pay, so the cost is considered "paid" by the AI (when it pays 0), from hence the effect that the card isn't sacrificed. It's easy enough to make it correctly "not pay" the cost at all, but I'm not sure how to make it choose to pay the cost when it can.
This is also relevant for cards such as Aether Spike (which the AI has no idea how to play at all) and most likely other cards with PayEnergy that has UnlessCost<N> or UnlessCost<X> and resolves to something complex enough. This will probably need custom AI logic on a case-by-case basis. I'll most likely patch the "cheaty" part for now, not sure what to do about the other cards tbh. Maybe marking them as AI-unplayable would be a good idea until we can come up with a good enough idea for how to make the AI work for them?

**Comment by Agetian** [comment]
The AI will do the same kind of cheating with Galvanic Discharge, for instance. It'll target the card and pay 0 energy (the same way as above), killing the targeted card (since it marks the cost as paid despite paying 0).

**Comment by Agetian** [comment]
Any suggestions, @Hanmac @tool4ever ?

**Comment by Hanmac** [comment]
@Agetian I will try to look at it over the weekend 

I need to refactor #1119 anyway

**Comment by Agetian** [comment]
Alrighty, thanks a lot for help!
