### ISSUE TITLE
Cannot view current deck in quest deck editor 

### ISSUE THREAD

**Issue by ConnectedWanderer** [Card-Forge/forge#6625]
**Describe the bug**
I cannot view the deck I am building in the quest deck editor. I click on cards on the left side but clicking on the "current deck" pannel does not do anything.

**To Reproduce**
1. Go to 'Quest Mode'
2. Start a new quest with default options
3. Go to the Quest deck window and click on "Build a New Deck"
4. In the Quest Deck Editor, add some cards from the inventory on the left
6. I cannot see my current deck and I have weird dots on the "Current deck" panel button (see screenshot)

**Expected behavior**
I should be able to see my current deck while building it.

**Screenshots**
![Issue with quest deck editor](https://github.com/user-attachments/assets/3d0a2890-76bf-40d2-ae69-7b5f51a5d541)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Java SDK 17 installed

**Additional context**
I attached the logs I have but I don't see any error message here.
[forge.log](https://github.com/user-attachments/files/17894383/forge.log)

**Comment by paulsnoops** [comment]
Try Game Settings > Preferences > Reset Editor Layout

![java_shjvOLrA0v](https://github.com/user-attachments/assets/25a3cc21-c2b0-461c-a09a-d2e95eb80fb5)

**Comment by ConnectedWanderer** [comment]
Thank you, resetting the layout fixes the issue. Is it a known bug ?

**Comment by Jetz72** [comment]
It's sort of a family of known issues. The desktop UI saves changes the user makes to their layout - rearranging and resizing panels and whatnot. There's a lot of freedom to manipulate it, it's manipulated programmatically too at times, and the way its saved is very thorough. So if some panel goes missing or gets arranged in a way that doesn't work properly, it stays that way across restarts, and nobody can figure out the original cause because it may have happened days ago when the user was looking at a completely different page.
