### ISSUE TITLE
Bloomburrow rabbit token image bug

### ISSUE THREAD

**Issue by jarohub** [Card-Forge/forge#6683]
**Describe the bug**
The Bloomburrow set "Rabbit" token name in the set description file and the filename image in the cards download server are not the same.
This bug makes that the rabbit token image never loads. 

**To Reproduce**
I've check the error in windows and android

**Expected behavior**
Show the card image.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows

**Smartphone (please complete the following information):**
 - Device: Google pixel

**Additional context**

**Comment by tehdiplomat** [comment]
Looks like its there to me. Maybe you just have a misdownload of it? 
https://downloads.cardforge.org/images/tokens/w_1_1_rabbit_blb.jpg

**Comment by tehdiplomat** [comment]
Yep.. downloaded just fine for me: 
![image](https://github.com/user-attachments/assets/d2a1d342-3b90-4409-ae25-6eec6e8f2138)

**Comment by jarohub** [comment]
First of all thanks for the free support. I love this program.


The token in question won't load with the "auto download missing card art" option.

If you have the images maybe downloaded or imported it will work. I dont know the program.
I've the same problem in android and Windows with the same cards not a coincidence.



I have checked the 2k tokens, one by one, passing the mouseover from inside the app and I have also a list of images that doesn't load , the other 2k images load without problems from cardforge server.


ape token (unh)
employee token (pcel)
treefolk token (dsc)
toy token (dsk)
rabbit (blb)
demon token (dsk)
insect token (dsk)
insect token (fdn)
everywhere (dsk)
gremlin token (dsk)
fish token (fdn)
shapeshifter token (dsc)
rabid sheep (ugl)
horror token (dsk)
spirit token (neo)
spirit token (dsk)
scion of the deep (fdn)
spider token (dsk)
primo, the indivisible (dsk)
beast token (dsk)
scarecrow token (dsc)
angel token
phyrexian goblin token (fdn)
dragon token (ust)
fractal token (dsc)
beeble token (und)
avatar token (yotj)
knight token (fdn)
glimmer token (dsk)
shrine token (sld)
ninja token (fdn)
rat token (fdn)
bird token (dsc)

**Comment by tehdiplomat** [comment]
I only use the autodownloader, and it loaded just fine for me. Maybe the download failed for you and its refusing to redownload? I'm not really sure. I don't think the tokens have been uploaded yet for the most recent sets, I wouldn't necessarily call that a "bug", it's just something we haven't gotten around to yet. 

Some of these older ones you claim aren't there I'm very suspicious of. Like NEO spirit has been on the server for 2 years? The token viewer has some flakiness inherit in it, so I'm guessing more likely some assumptions you are making about it makes you think the images aren't available even if they are. I would just let the game download it when you use it, rather than worry about the token viewer.
