### ISSUE TITLE
Genju's don't return from grave.

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Card-Forge/forge#983]
When a land enchanted by a Genju goes to the graveyard, the Genju's effect triggers, and asks whether you want to return it, but if you say yes, it stays in the graveyard. I'm not sure why this isn't working, since the card script appears to specifically move it from the graveyard to the hand. Perhaps the Genju is treated as a different object once it entered the grave, causing it to lose the reference to itself? (since the triggered ability technically triggers from the battlefield ?)

However, you should be careful when you fix this.

If another player steals control of the genju, and the land then dies, the ability should indeed do nothing, since it's impossible for the controller to move it from their graveyard to their hand, since it is actually in the other player's graveyard. It doesn't return to its owner's hand either, because it is attempting to find it in its controller's graveyard.
It also doesn't trigger for its owner, since 'you' refers to the last-known controller of Genju in this case.

So the correct way to do this:

When the enchanted land is put into the graveyard from the battlefield, the last-known controller of the Genju puts the trigger on the stack.
At resolution of the trigger, they choose yes or no.
If no, nothing happens.
If yes, and the Genju is in their graveyard, it is returned to their hand.
If yes, and the Genju is in another player's graveyard (or anywhere else), nothing happens.

**Comment by Hanmac** [comment]
The problem is that you can't use LKI of Genju there, or you would get the wrong infomation

because the moment when the land is send to the graveyard, and the Trigger is created, Genju is still on the battlefield enchanting nothing. (at this moment it uses LKI)
only later StateBasedAction are run and Genju is sent to the graveyard.
Now Genju is put into graveyard.
Now Trigger is put on the Stack. But the host of the Trigger now has wrong timestamp.

one possible fix is that before the moment the trigger is put on the stack it updates the host card, but the Trigger controller should still be the LKI controller.
But that should only happen for some trigger, doing it for all of them could be problematic, like adding counters to creatures in the graveyard.

**Comment by Grim-the-Reaper** [comment]
It looks like Forge just doesn't handle this rule very well:

400.7e Abilities of Auras that trigger when the enchanted permanent leaves the battlefield can find the new object that Aura became in its owner’s graveyard if it was put into that graveyard at the same time the enchanted permanent left the battlefield. It can also find the new object that Aura became in its owner’s graveyard as a result of being put there as a state-based action for not being attached to a permanent. (See rule 704.5m.)
